# Generated by Django 6.0.6 on 2026-06-20 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_tour_contactmessage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
