# Generated by Django 6.0.6 on 2026-06-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bookingrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourpackage',
            options={},
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='highlights',
            field=models.TextField(blank=True, help_text='One highlight per line'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='included',
            field=models.TextField(blank=True, help_text='One inclusion per line'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='duration',
            field=models.CharField(max_length=50),
        ),
    ]
