# Generated by Django 6.0.6 on 2026-06-21 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_contactmessage_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the safari expedition.', max_length=200)),
                ('description', models.TextField(help_text='Detailed overview and route details.')),
                ('image', models.ImageField(blank=True, help_text='Main hero showcase photograph.', null=True, upload_to='tours/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Cost in USD.', max_digits=10, null=True)),
                ('location', models.CharField(blank=True, help_text='e.g., Queen Elizabeth National Park', max_length=150, null=True)),
                ('duration', models.CharField(blank=True, help_text='e.g., 3 Days, 2 Nights', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Safari Tour',
                'verbose_name_plural': 'Safari Tours',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.tour'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.tour'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='core.tour'),
        ),
        migrations.DeleteModel(
            name='TourPackage',
        ),
    ]
