# Generated by Django 6.0.6 on 2026-06-22 07:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tour_alter_bookingrequest_package_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={},
        ),
        migrations.RemoveField(
            model_name='tour',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='location',
        ),
        migrations.AddField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='destination',
            field=models.CharField(default='Uganda', max_length=150),
        ),
        migrations.AddField(
            model_name='tour',
            name='detailed_itinerary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, help_text='Duration of the safari in days'),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='short_description',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost in USD or UGX', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
