# Generated by Django 6.0.6 on 2026-06-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tour_alter_tourpackage_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
